/**
 * index.ts — Main entry point.
 *
 * Boots services in order:
 * 1. DB (Prisma migrations)
 * 2. Redis (command + subscriber connections)
 * 3. Solana RPC circuit breaker
 * 4. REST API server
 * 5. WebSocket server
 * 6. Solana event listener
 * 7. Settlement keeper
 *
 * Graceful shutdown on SIGTERM/SIGINT.
 */

import 'dotenv/config';
import crypto from 'crypto';
import { PublicKey } from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';

import { config } from './config';
import { logger } from './logger';
import { connectDb, disconnectDb } from './db';
import { connectRedis, disconnectRedis } from './redis';
import { createApiServer, startApiServer } from './api/server';
import { startWsServer } from './websocket/wsServer';
import { startEventListener, stopEventListener } from './listener/eventListener';
import { runBackfiller } from './listener/backfiller';
import { startSettlementKeeper } from './keeper/settlementKeeper';
import { runTwapCron } from './keeper/twapCron';
import { RpcCircuitBreaker } from './solana/rpcCircuitBreaker';

function computeInstructionDiscriminator(name: string): number[] {
  // Convert camelCase to snake_case (e.g., createRoom -> create_room)
  const snakeCase = name.replace(/([A-Z])/g, '_$1').toLowerCase();
  const preimage = `global:${snakeCase}`;
  const hash = crypto.createHash('sha256').update(preimage).digest();
  return Array.from(hash.slice(0, 8));
}

function computeAccountDiscriminator(name: string): number[] {
  // Ensure the preimage uses the PascalCase name (e.g. platformConfig -> PlatformConfig)
  const pascalName = name.charAt(0).toUpperCase() + name.slice(1);
  const preimage = `account:${pascalName}`;
  const hash = crypto.createHash('sha256').update(preimage).digest();
  return Array.from(hash.slice(0, 8));
}


function buildAnchorProgram(circuitBreaker: RpcCircuitBreaker): {
  program: anchor.Program;
  eventParser: anchor.EventParser;
} {
  const programId = new PublicKey(config.solana.programId);
  const connection = circuitBreaker.getConnection();

  // Minimal wallet for read-only provider (event listener doesn't sign)
  const wallet = new anchor.Wallet(anchor.web3.Keypair.generate());
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });

  // Load IDL — generated by `anchor build`, stored as JSON
  // In development: resolve from program/target/idl/shitmarket.json or fallback to src/utils/idl.json
  let idl: anchor.Idl;
  try {
    idl = require('../../program/target/idl/shitmarket.json') as anchor.Idl;
    logger.info('Loaded IDL from anchor build output');
  } catch {
    try {
      idl = require('./utils/idl.json') as anchor.Idl;
      logger.info('Loaded IDL from frontend source utils/idl.json');
    } catch {
      logger.warn('Could not load anchor IDL — using minimal fallback. Run `anchor build` first.');
      idl = {
      version: '0.1.0',
      name: 'shitmarket',
      instructions: [],
      accounts: [],
      events: [
        {
          name: 'RoomCreated',
          fields: [
            { name: 'room', type: 'publicKey', index: false },
            { name: 'creator', type: 'publicKey', index: false },
            { name: 'tokenMint', type: 'publicKey', index: false },
            { name: 'tokenName', type: 'string', index: false },
            { name: 'priceFeed', type: 'publicKey', index: false },
            { name: 'openingPrice', type: 'i64', index: false },
            { name: 'durationMinutes', type: 'u32', index: false },
            { name: 'expiryTimestamp', type: 'i64', index: false },
          ],
        },
        {
          name: 'BetPlaced',
          fields: [
            { name: 'room', type: 'publicKey', index: false },
            { name: 'user', type: 'publicKey', index: false },
            { name: 'side', type: 'u8', index: false },
            { name: 'amount', type: 'u64', index: false },
            { name: 'moonPool', type: 'u64', index: false },
            { name: 'jeetPool', type: 'u64', index: false },
          ],
        },
        {
          name: 'RoomSettled',
          fields: [
            { name: 'room', type: 'publicKey', index: false },
            { name: 'winner', type: 'u8', index: false },
            { name: 'openingPrice', type: 'i64', index: false },
            { name: 'finalPrice', type: 'i64', index: false },
            { name: 'totalPool', type: 'u64', index: false },
            { name: 'platformFee', type: 'u64', index: false },
          ],
        },
        {
          name: 'WinningsClaimed',
          fields: [
            { name: 'room', type: 'publicKey', index: false },
            { name: 'user', type: 'publicKey', index: false },
            { name: 'amount', type: 'u64', index: false },
          ],
        },
        {
          name: 'RoomVoided',
          fields: [
            { name: 'room', type: 'publicKey', index: false },
            { name: 'totalRefundPool', type: 'u64', index: false },
            { name: 'reason', type: 'string', index: false },
          ],
        },
      ],
      errors: [],
    } as unknown as anchor.Idl;
    }
  }

  // Ensure IDL user-defined types use modern Anchor v0.30 format
  function normalizeIdl(obj: any): void {
    if (Array.isArray(obj)) {
      obj.forEach(normalizeIdl);
    } else if (obj !== null && typeof obj === 'object') {
      for (const key in obj) {
        if (key === 'defined' && typeof obj[key] === 'string') {
          obj[key] = { name: obj[key] };
        } else {
          normalizeIdl(obj[key]);
        }
      }
    }
  }
  normalizeIdl(idl);

  // Dynamically compute instruction discriminators if missing in the IDL
  if (idl && idl.instructions) {
    idl.instructions = idl.instructions.map((ix: any) => {
      if (!ix.discriminator) {
        ix.discriminator = computeInstructionDiscriminator(ix.name);
      }
      return ix;
    });
  }

  // Map idl.accounts and idl.types to use camelCase account names and attach computed discriminators
  if (idl && idl.accounts) {
    const newTypes: any[] = idl.types ? [...idl.types] : [];
    
    idl.accounts = idl.accounts.map((acc: any) => {
      const originalName = acc.name; // e.g. "PlatformConfig"
      const camelName = originalName.charAt(0).toLowerCase() + originalName.slice(1);
      
      // Update account name to camelCase
      acc.name = camelName;
      if (!acc.discriminator) {
        acc.discriminator = computeAccountDiscriminator(originalName);
      }
      
      // Copy the account type definition into types so that BorshAccountsCoder finds it
      if (!newTypes.some((ty: any) => ty.name === camelName)) {
        newTypes.push({
          name: camelName,
          type: acc.type
        });
      }
      
      return acc;
    });
    
    idl.types = newTypes;
  }

  // In anchor v0.30, Program constructor is: new Program(idl, provider)
  // The programId is read from the IDL's `address` field or passed via provider.
  // We set the address on the IDL object directly as a workaround for the
  // fallback IDL which has no address field.
  const idlWithAddress = { ...idl, address: programId.toBase58() };
  const program = new anchor.Program(idlWithAddress as anchor.Idl, provider);
  const eventParser = new anchor.EventParser(programId, new anchor.BorshCoder(idlWithAddress as anchor.Idl));

  return { program, eventParser };
}

// ─── Graceful shutdown ────────────────────────────────────────────────────────

async function shutdown(circuitBreaker: RpcCircuitBreaker): Promise<void> {
  logger.info('Shutting down ShitMarket indexer...');
  circuitBreaker.shutdown();
  await disconnectDb();
  await disconnectRedis();
  process.exit(0);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  logger.info({ msg: 'Starting ShitMarket indexer', env: config.nodeEnv });

  // 1. Database
  await connectDb();

  // 2. Redis
  await connectRedis();

  // 3. Solana RPC circuit breaker (auto-failover to secondary)
  const circuitBreaker = new RpcCircuitBreaker(
    config.solana.rpcUrl,
    config.solana.secondaryRpcUrl || undefined
  );
  const connection = circuitBreaker.getConnection();

  const slot = await connection.getSlot();
  logger.info({ msg: 'Solana RPC connected', slot, rpc: config.solana.rpcUrl });
  circuitBreaker.reportSuccess();

  // 4. Anchor program + event parser
  const { program, eventParser } = buildAnchorProgram(circuitBreaker);

  // 5. REST API
  const app = createApiServer(circuitBreaker);
  startApiServer(app);

  // 6. WebSocket server
  startWsServer();

  // 7. Event listener
  startEventListener(connection, eventParser);

  // 8. Settlement keeper
  startSettlementKeeper(connection, program);

  // 9. TWAP Cron
  setInterval(() => {
    runTwapCron().catch(err => logger.error({ msg: 'twapCron failed', error: err }));
  }, 60000);

  // 10. Self-Healing Backfiller failsafe (Startup run + 60-second interval)
  runBackfiller(connection, program, eventParser).catch(err =>
    logger.error({ msg: 'Startup self-healing backfiller failed', error: err })
  );
  setInterval(() => {
    runBackfiller(connection, program, eventParser).catch(err =>
      logger.error({ msg: 'Interval self-healing backfiller failed', error: err })
    );
  }, 60000);

  // Graceful shutdown handlers
  process.on('SIGTERM', () => shutdown(circuitBreaker));
  process.on('SIGINT', () => shutdown(circuitBreaker));
  process.on('uncaughtException', (err) => {
    logger.fatal({ msg: 'Uncaught exception', err: err.message, stack: err.stack });
    process.exit(1);
  });
  process.on('unhandledRejection', (reason) => {
    logger.error({ msg: 'Unhandled rejection', reason });
  });

  logger.info('All services started successfully 🚀');
}

main().catch((err) => {
  logger.fatal({ msg: 'Fatal startup error', err: err?.message, stack: err?.stack });
  process.exit(1);
});
