import * as anchor from "@coral-xyz/anchor";
import { BN, AnchorError } from "@coral-xyz/anchor";

import {
  Keypair,
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
} from "@solana/web3.js";
import { assert, expect } from "chai";
// Note: Shitmarket type is generated by `anchor build` into target/types/shitmarket.json
// Until the first build runs we define a minimal alias so TypeScript is happy.
type Shitmarket = any; // replaced with `import { Shitmarket } from "../target/types/shitmarket"` after `anchor build`


// ─────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────

async function airdrop(
  provider: anchor.AnchorProvider,
  pubkey: PublicKey,
  sol: number
) {
  const sig = await provider.connection.requestAirdrop(
    pubkey,
    sol * LAMPORTS_PER_SOL
  );
  await provider.connection.confirmTransaction(sig, "confirmed");
}

function deriveConfig(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("platform_config")],
    programId
  );
}

function deriveRoom(
  tokenMint: PublicKey,
  creator: PublicKey,
  programId: PublicKey,
  nonce: number = 0
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("room"), tokenMint.toBuffer(), creator.toBuffer(), Buffer.from([nonce])],
    programId
  );
}

function deriveBet(
  room: PublicKey,
  user: PublicKey,
  side: "moon" | "jeet",
  programId: PublicKey
): [PublicKey, number] {
  const sideByte = side === "moon" ? 0 : 1;
  return PublicKey.findProgramAddressSync(
    [Buffer.from("bet"), room.toBuffer(), user.toBuffer(), Buffer.from([sideByte])],
    programId
  );
}

function deriveEscrow(room: PublicKey, programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), room.toBuffer()],
    programId
  );
}

function deriveReputation(
  user: PublicKey,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("reputation"), user.toBuffer()],
    programId
  );
}

function deriveLimitOrder(
  user: PublicKey,
  room: PublicKey,
  nonce: number,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("limit_order"), user.toBuffer(), room.toBuffer(), Buffer.from([nonce])],
    programId
  );
}

// Mock token mint — we only store its pubkey on-chain, no real SPL mint needed
const MOCK_TOKEN_MINT = Keypair.generate().publicKey;
const MOCK_TOKEN_NAME = "PEPE5";
const MOCK_PRICE_FEED = Keypair.generate();
const MOCK_OPENING_PRICE = new BN(1_500_000_000); // $150.00 mock price

async function createFakePythFeedAccount(provider: anchor.AnchorProvider, feedKeypair: Keypair) {
  const lamports = await provider.connection.getMinimumBalanceForRentExemption(2048);
  const tx = new anchor.web3.Transaction().add(
    SystemProgram.createAccount({
      fromPubkey: provider.wallet.publicKey,
      newAccountPubkey: feedKeypair.publicKey,
      lamports,
      space: 2048,
      programId: SystemProgram.programId,
    })
  );
  await provider.sendAndConfirm(tx, [feedKeypair]);
}

// ─────────────────────────────────────────────
//  Test Suite
// ─────────────────────────────────────────────

describe("shitmarket", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = anchor.workspace.Shitmarket as any; // typed as any until `anchor build` generates ../target/types/shitmarket
  const programId: PublicKey = (program as { programId: PublicKey }).programId;


  // Wallets
  const admin = Keypair.generate();
  const treasury = Keypair.generate();
  const keeper = Keypair.generate();
  const creator = Keypair.generate();
  const moonBettor = Keypair.generate();
  const jeetBettor = Keypair.generate();
  const secondMoonBettor = Keypair.generate();
  const whaleBettor = Keypair.generate(); // for bet limit tests

  // PDAs (populated in tests)
  let configPda: PublicKey;
  let roomPda: PublicKey;
  let escrowPda: PublicKey;
  let moonBetPda: PublicKey;
  let jeetBetPda: PublicKey;
  let secondMoonBetPda: PublicKey;
  let whaleBetPda: PublicKey;
  let whaleRepPda: PublicKey;

  before(async () => {
    // Fund all wallets
    await Promise.all([
      airdrop(provider, admin.publicKey, 10),
      airdrop(provider, treasury.publicKey, 1),
      airdrop(provider, creator.publicKey, 5),
      airdrop(provider, moonBettor.publicKey, 5),
      airdrop(provider, jeetBettor.publicKey, 5),
      airdrop(provider, secondMoonBettor.publicKey, 5),
      airdrop(provider, whaleBettor.publicKey, 200),
    ]);

    await createFakePythFeedAccount(provider, MOCK_PRICE_FEED);

    [configPda] = deriveConfig(programId);
    [roomPda] = deriveRoom(MOCK_TOKEN_MINT, creator.publicKey, programId);
    [escrowPda] = deriveEscrow(roomPda, programId);
    [moonBetPda] = deriveBet(roomPda, moonBettor.publicKey, "moon", programId);
    [jeetBetPda] = deriveBet(roomPda, jeetBettor.publicKey, "jeet", programId);
    [secondMoonBetPda] = deriveBet(roomPda, secondMoonBettor.publicKey, "moon", programId);
    [whaleBetPda] = deriveBet(roomPda, whaleBettor.publicKey, "moon", programId);
    [whaleRepPda] = deriveReputation(whaleBettor.publicKey, programId);
  });

  // ── 1. Initialize ─────────────────────────────────────────────────────

  it("initializes platform config with 2% fee", async () => {
    await program.methods
      .initialize(125) // 125 bps = 1.25%
      .accounts({
        config: configPda,
        admin: admin.publicKey,
        treasury: treasury.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([admin])
      .rpc();

    const config = await program.account.platformConfig.fetch(configPda);
    assert.equal(config.admin.toBase58(), admin.publicKey.toBase58());
    assert.equal(config.treasury.toBase58(), treasury.publicKey.toBase58());
    assert.equal(config.platformFeeBps, 125);
    assert.equal(config.paused, false, "Should start unpaused");
  });

  it("rejects fee > 10%", async () => {
    try {
      await program.methods
        .updateConfig(1001, null, null, null, null)
        .accounts({
          config: configPda,
          admin: admin.publicKey,
          newTreasury: null,
        })
        .signers([admin])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      expect(err.message).to.include("FeeTooHigh");
    }
  });

  // ── 2. Create Room ────────────────────────────────────────────────────

  it("creates a room with 30-minute duration", async () => {
    await program.methods
      .createRoom(
        MOCK_TOKEN_MINT,
        MOCK_TOKEN_NAME,
        30, // 30 minutes
        null, // no switchboard feed
        null, // no opening price override
        0 // nonce
      )
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        creator: creator.publicKey,
        priceFeed: MOCK_PRICE_FEED.publicKey,
        switchboardFeed: PublicKey.default,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([creator])
      .rpc();

    const room = await program.account.room.fetch(roomPda);
    assert.equal(room.tokenMint.toBase58(), MOCK_TOKEN_MINT.toBase58());
    assert.equal(room.durationMinutes, 30);
    assert.isTrue(room.openingPrice.eq(MOCK_OPENING_PRICE));
    assert.equal(room.moonPool.toNumber(), 0);
    assert.equal(room.jeetPool.toNumber(), 0);
    assert.deepEqual(room.status, { active: {} });
    assert.isNull(room.winner);
    assert.equal(room.switchboardFeed.toBase58(), PublicKey.default.toBase58(), "Switchboard feed should be default");
  });

  it("rejects invalid durations", async () => {
    const otherMint = Keypair.generate().publicKey;
    const [otherRoom] = deriveRoom(otherMint, creator.publicKey, programId);
    try {
      await program.methods
        .createRoom(otherMint, "BAD", 0, null, null, 0)
        .accounts({
          room: otherRoom,
          escrow: deriveEscrow(otherRoom, programId)[0],
          creator: creator.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([creator])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      expect(err.message).to.include("InvalidDuration");
    }
  });

  // ── 2b. Phase 3.3: Pause/Unpause ──────────────────────────────────────

  it("rejects room creation when paused (Phase 3.3)", async () => {
    // Pause the platform
    await program.methods
      .pause()
      .accounts({ config: configPda, admin: admin.publicKey })
      .signers([admin])
      .rpc();

    const configPaused = await program.account.platformConfig.fetch(configPda);
    assert.equal(configPaused.paused, true);

    const pausedMint = Keypair.generate().publicKey;
    const [pausedRoom] = deriveRoom(pausedMint, creator.publicKey, programId);
    try {
      await program.methods
        .createRoom(pausedMint, "PAUSED", 5, null, null, 0)
        .accounts({
          room: pausedRoom,
          escrow: deriveEscrow(pausedRoom, programId)[0],
          creator: creator.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([creator])
        .rpc();
      assert.fail("Should have thrown — platform is paused");
    } catch (err: any) {
      expect(err.message).to.include("Paused");
    }

    // Unpause for remaining tests
    await program.methods
      .unpause()
      .accounts({ config: configPda, admin: admin.publicKey })
      .signers([admin])
      .rpc();

    const configUnpaused = await program.account.platformConfig.fetch(configPda);
    assert.equal(configUnpaused.paused, false);
  });

  it("rejects non-admin from pausing", async () => {
    try {
      await program.methods
        .pause()
        .accounts({ config: configPda, admin: creator.publicKey })
        .signers([creator])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      expect(err.message).to.include("Unauthorized");
    }
  });

  // ── 3. Place Bets ─────────────────────────────────────────────────────

  it("places a bet on Moon side (1 SOL)", async () => {
    const betAmount = new BN(1 * LAMPORTS_PER_SOL);

    await program.methods
      .placeBet({ moon: {} }, betAmount)
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        bet: moonBetPda,
        user: moonBettor.publicKey,
        reputation: null as any,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([moonBettor])
      .rpc();

    const room = await program.account.room.fetch(roomPda);
    assert.isTrue(room.moonPool.eq(betAmount));
    assert.isTrue(room.jeetPool.eq(new BN(0)));

    const bet = await program.account.bet.fetch(moonBetPda);
    assert.isTrue(bet.amount.eq(betAmount));
    assert.deepEqual(bet.side, { moon: {} });
    assert.isFalse(bet.claimed);
  });

  it("places a bet on Jeet side (0.5 SOL)", async () => {
    const betAmount = new BN(0.5 * LAMPORTS_PER_SOL);

    await program.methods
      .placeBet({ jeet: {} }, betAmount)
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        bet: jeetBetPda,
        user: jeetBettor.publicKey,
        reputation: null as any,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([jeetBettor])
      .rpc();

    const room = await program.account.room.fetch(roomPda);
    assert.isTrue(room.jeetPool.eq(betAmount));
  });

  it("adds to an existing Moon bet (another 0.5 SOL)", async () => {
    const extraAmount = new BN(0.5 * LAMPORTS_PER_SOL);

    await program.methods
      .placeBet({ moon: {} }, extraAmount)
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        bet: moonBetPda,
        user: moonBettor.publicKey,
        reputation: null as any,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([moonBettor])
      .rpc();

    const bet = await program.account.bet.fetch(moonBetPda);
    // 1 SOL + 0.5 SOL = 1.5 SOL
    assert.isTrue(bet.amount.eq(new BN(1.5 * LAMPORTS_PER_SOL)));
  });

  it("places a second Moon bettor (0.5 SOL)", async () => {
    const betAmount = new BN(0.5 * LAMPORTS_PER_SOL);
    await program.methods
      .placeBet({ moon: {} }, betAmount)
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        bet: secondMoonBetPda,
        user: secondMoonBettor.publicKey,
        reputation: null as any,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([secondMoonBettor])
      .rpc();

    const room = await program.account.room.fetch(roomPda);
    // 1.5 + 0.5 = 2 SOL moon pool
    assert.isTrue(room.moonPool.eq(new BN(2 * LAMPORTS_PER_SOL)));
  });

  it("rejects zero-amount bets", async () => {
    try {
      await program.methods
        .placeBet({ moon: {} }, new BN(0))
        .accounts({
          room: roomPda,
          escrow: escrowPda,
          bet: moonBetPda,
          user: moonBettor.publicKey,
          reputation: null as any,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([moonBettor])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      expect(err.message).to.include("ZeroBetAmount");
    }
  });

  // ── 3b. Phase 3.5: Reputation + Bet Limit Tests ───────────────────────

  it("rejects bet exceeding D-tier limit without reputation (Phase 3.5)", async () => {
    // Default tier D limit = 1 SOL. Try to bet 2 SOL.
    try {
      await program.methods
        .placeBet({ moon: {} }, new BN(2 * LAMPORTS_PER_SOL))
        .accounts({
          room: roomPda,
          escrow: escrowPda,
          bet: whaleBetPda,
          user: whaleBettor.publicKey,
          reputation: null as any,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([whaleBettor])
        .rpc();
      assert.fail("Should have thrown — exceeds D tier limit");
    } catch (err: any) {
      expect(err.message).to.include("BetAmountExceedsLimit");
    }
  });

  it("allows bet within D-tier limit", async () => {
    // 1 SOL is the D tier max
    await program.methods
      .placeBet({ moon: {} }, new BN(LAMPORTS_PER_SOL))
      .accounts({
        room: roomPda,
        escrow: escrowPda,
        bet: whaleBetPda,
        user: whaleBettor.publicKey,
        reputation: null as any,
        config: configPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([whaleBettor])
      .rpc();

    const bet = await program.account.bet.fetch(whaleBetPda);
    assert.isTrue(bet.amount.eq(new BN(LAMPORTS_PER_SOL)));
  });

  it("initializes reputation and allows higher-tier bets (Phase 3.5)", async () => {
    // Initialize reputation for whaleBettor
    const [repPda] = deriveReputation(whaleBettor.publicKey, programId);

    await program.methods
      .initializeReputation()
      .accounts({
        reputation: repPda,
        user: whaleBettor.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([whaleBettor])
      .rpc();

    const rep = await program.account.reputation.fetch(repPda);
    assert.deepEqual(rep.tier, { d: {} });
    assert.equal(rep.totalBets.toNumber(), 0);
    assert.equal(rep.totalWins.toNumber(), 0);
  });

  // ── 4. Settle Room ────────────────────────────────────────────────────

    it("rejects settlement before expiry", async () => {
      const higherPrice = MOCK_OPENING_PRICE.addn(5_000);
      try {
        await program.methods
          .settleRoom(null)
          .accounts({
            room: roomPda,
            escrow: escrowPda,
            treasury: treasury.publicKey,
            priceFeed: MOCK_PRICE_FEED.publicKey,
            switchboardFeed: PublicKey.default,
            config: configPda,
            keeper: admin.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([admin])
          .rpc();
        assert.fail("Should have thrown — room not expired");
      } catch (err: any) {
        expect(err.message).to.include("RoomNotExpired");
      }
    });

  it("settles room after expiry with Moon winning price", async () => {
    // Wait for 5-minute room to expire (300s). In real tests use fast-forward;
    // here we wait just enough for localnet (set room to 5s for this test).
    // For the purpose of this suite we'll create a separate "fast" room below.
    // The 5-minute room tests above are valid structural tests; settlement is
    // tested with a fast-expiry room in the next block.
    console.log("  Skipping live expiry wait for 5min room — see fast-room tests below.");
  });

  // ── 4b. Fast-Expiry Room for Settlement Tests ─────────────────────────

  describe("fast-expiry settlement flow", () => {
    const fastMint = Keypair.generate().publicKey;
    const fastCreator = Keypair.generate();
    let fastRoomPda: PublicKey;
    let fastEscrowPda: PublicKey;
    let fastMoonBetPda: PublicKey;
    let fastJeetBetPda: PublicKey;
    const fastMoonBettor = Keypair.generate();
    const fastJeetBettor = Keypair.generate();

    before(async () => {
      await Promise.all([
        airdrop(provider, fastCreator.publicKey, 3),
        airdrop(provider, fastMoonBettor.publicKey, 3),
        airdrop(provider, fastJeetBettor.publicKey, 3),
      ]);

      [fastRoomPda] = deriveRoom(fastMint, fastCreator.publicKey, programId);
      [fastEscrowPda] = deriveEscrow(fastRoomPda, programId);
      [fastMoonBetPda] = deriveBet(fastRoomPda, fastMoonBettor.publicKey, "moon", programId);
      [fastJeetBetPda] = deriveBet(fastRoomPda, fastJeetBettor.publicKey, "jeet", programId);
    });

    it("creates a fast room (10-min — expires quickly in localnet warp)", async () => {
      await program.methods
        .createRoom(fastMint, "FASTTOKEN", 10, null, null, 0)
        .accounts({
          room: fastRoomPda,
          escrow: fastEscrowPda,
          creator: fastCreator.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([fastCreator])
        .rpc();
    });

    it("places bets on both sides of fast room", async () => {
      // Moon: 1 SOL
      await program.methods
        .placeBet({ moon: {} }, new BN(LAMPORTS_PER_SOL))
        .accounts({
          room: fastRoomPda,
          escrow: fastEscrowPda,
          bet: fastMoonBetPda,
          user: fastMoonBettor.publicKey,
          reputation: null as any,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([fastMoonBettor])
        .rpc();

      // Jeet: 0.5 SOL
      await program.methods
        .placeBet({ jeet: {} }, new BN(0.5 * LAMPORTS_PER_SOL))
        .accounts({
          room: fastRoomPda,
          escrow: fastEscrowPda,
          bet: fastJeetBetPda,
          user: fastJeetBettor.publicKey,
          reputation: null as any,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([fastJeetBettor])
        .rpc();

      const room = await program.account.room.fetch(fastRoomPda);
      assert.isTrue(room.moonPool.eq(new BN(LAMPORTS_PER_SOL)));
      assert.isTrue(room.jeetPool.eq(new BN(0.5 * LAMPORTS_PER_SOL)));
    });

    // NOTE: The following tests require the room to be expired.
    // Run with `anchor test -- --timeout 400000` and the localnet
    // must have fast slot times, OR warp clock using test-validator flags.
    // For CI, use: solana-test-validator --limit-ledger-size 50000000 &
    // and set BPF_LOADER_UPGRADEABLE=1

    it("(TIME-DEPENDENT) settles room after expiry — Moon wins", async function () {
      this.timeout(400_000);
      const fastRoom = await program.account.room.fetch(fastRoomPda);
      const now = Math.floor(Date.now() / 1000);
      const waitMs = (fastRoom.expiryTimestamp.toNumber() - now + 2) * 1000;

      if (waitMs > 0) {
        console.log(`  Waiting ${Math.ceil(waitMs / 1000)}s for room to expire...`);
        await new Promise((r) => setTimeout(r, waitMs));
      }

      const finalPrice = new BN(2_000_000_000); // $200.00 > $150.00 opening → Moon wins
      const treasuryBefore = await provider.connection.getBalance(treasury.publicKey);

      await program.methods
        .settleRoom(new BN(2_000_000_000))
        .accounts({
          room: fastRoomPda,
          escrow: fastEscrowPda,
          treasury: treasury.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          keeper: keeper.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([keeper])
        .rpc();

      const room = await program.account.room.fetch(fastRoomPda);
      assert.deepEqual(room.status, { settled: {} });
      assert.deepEqual(room.winner, { moon: {} });
      assert.isTrue(room.finalPrice.eq(finalPrice));
      assert.isTrue(room.twapFinalPrice.gt(new BN(0)), "TWAP final price should be set");

      // Verify platform fee arrived at treasury
      // Total pool = 1.5 SOL; fee = 1.25% = 0.01875 SOL = 18_750_000 lamports
      const treasuryAfter = await provider.connection.getBalance(treasury.publicKey);
      const feeReceived = treasuryAfter - treasuryBefore;
      assert.isAtLeast(feeReceived, 18_000_000, "Treasury should receive ~1.25% fee");
    });

    it("(TIME-DEPENDENT) winning Moon bettor claims proportional winnings", async function () {
      this.timeout(30_000);

      const userBefore = await provider.connection.getBalance(fastMoonBettor.publicKey);
      const escrowBefore = await provider.connection.getBalance(fastEscrowPda);
      console.log(`  Escrow balance before claim: ${escrowBefore / LAMPORTS_PER_SOL} SOL`);

      await program.methods
        .claimWinnings()
        .accounts({
          room: fastRoomPda,
          config: configPda,
          escrow: fastEscrowPda,
          bet: fastMoonBetPda,
          user: fastMoonBettor.publicKey,
          payer: fastMoonBettor.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([fastMoonBettor])
        .rpc();

      const userAfter = await provider.connection.getBalance(fastMoonBettor.publicKey);
      const gain = userAfter - userBefore;
      console.log(`  Moon bettor gained: ${gain / LAMPORTS_PER_SOL} SOL`);
      assert.isAbove(gain, 0, "Winner should receive lamports");

      const bet = await program.account.bet.fetch(fastMoonBetPda);
      assert.isTrue(bet.claimed, "Bet should be marked claimed");
    });

    it("rejects double-claim", async function () {
      try {
        await program.methods
          .claimWinnings()
          .accounts({
            room: fastRoomPda,
            config: configPda,
            escrow: fastEscrowPda,
            bet: fastMoonBetPda,
            user: fastMoonBettor.publicKey,
            payer: fastMoonBettor.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([fastMoonBettor])
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        expect(err.message).to.include("AlreadyClaimed");
      }
    });

    it("Jeet bettor cannot claim on Moon-winning room", async function () {
      try {
        await program.methods
          .claimWinnings()
          .accounts({
            room: fastRoomPda,
            config: configPda,
            escrow: fastEscrowPda,
            bet: fastJeetBetPda,
            user: fastJeetBettor.publicKey,
            payer: fastJeetBettor.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([fastJeetBettor])
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        expect(err.message).to.include("NotAWinner");
      }
    });

    it("rejects double settlement", async function () {
      try {
        await program.methods
          .settleRoom(new BN(2_000_000_000))
          .accounts({
            room: fastRoomPda,
            escrow: fastEscrowPda,
            treasury: treasury.publicKey,
            priceFeed: MOCK_PRICE_FEED.publicKey,
            switchboardFeed: PublicKey.default,
            config: configPda,
            keeper: keeper.publicKey,
            systemProgram: SystemProgram.programId,
          })
          .signers([keeper])
          .rpc();
        assert.fail("Should have thrown");
      } catch (err: any) {
        expect(err.message).to.include("RoomNotActive");
      }
    });
  });

  // ── 5. Update Config ─────────────────────────────────────────────────

  it("admin updates fee to 1%", async () => {
    await program.methods
      .updateConfig(100, null, null, null, null) // 100 bps = 1%
      .accounts({
        config: configPda,
        admin: admin.publicKey,
        newTreasury: null,
      })
      .signers([admin])
      .rpc();

    const config = await program.account.platformConfig.fetch(configPda);
    assert.equal(config.platformFeeBps, 100);

    // Revert fee back to 1.25% for subsequent tests
    await program.methods
      .updateConfig(125, null, null, null, null)
      .accounts({
        config: configPda,
        admin: admin.publicKey,
        newTreasury: null,
      })
      .signers([admin])
      .rpc();
  });

  it("non-admin cannot update config", async () => {
    try {
      await program.methods
        .updateConfig(50, null, null, null, null)
        .accounts({
          config: configPda,
          admin: creator.publicKey,
          newTreasury: null,
        })
        .signers([creator])
        .rpc();
      assert.fail("Should have thrown");
    } catch (err: any) {
      expect(err.message).to.include("Unauthorized");
    }
  });

  // ── 5b. Phase 3: Update config with new params ────────────────────────

  it("admin updates keeper, min liquidity, and twap window (Phase 3)", async () => {
    const newKeeper = Keypair.generate().publicKey;
    await program.methods
      .updateConfig(null, null, newKeeper, new BN(200_000_000), new BN(600))
      .accounts({
        config: configPda,
        admin: admin.publicKey,
        newTreasury: null,
      })
      .signers([admin])
      .rpc();

    const config = await program.account.platformConfig.fetch(configPda);
    assert.equal(config.keeper.toBase58(), newKeeper.toBase58());

    // Revert keeper back to the original keeper for subsequent tests
    await program.methods
      .updateConfig(null, null, keeper.publicKey, null, null)
      .accounts({
        config: configPda,
        admin: admin.publicKey,
        newTreasury: null,
      })
      .signers([admin])
      .rpc();
    assert.isTrue(config.minimumLiquidity.eq(new BN(200_000_000)), "Min liquidity should be 0.2 SOL");
    assert.isTrue(config.twapWindowSeconds.eq(new BN(600)), "TWAP window should be 600s");
  });

  // ── 6. Edge Cases ─────────────────────────────────────────────────────

  describe("edge cases", () => {
    const edgeMint = Keypair.generate().publicKey;
    const edgeCreator = Keypair.generate();
    const lonelyBettor = Keypair.generate();
    let edgeRoomPda: PublicKey;
    let edgeEscrowPda: PublicKey;
    let lonelyBetPda: PublicKey;

    before(async () => {
      await Promise.all([
        airdrop(provider, edgeCreator.publicKey, 3),
        airdrop(provider, lonelyBettor.publicKey, 3),
      ]);
      [edgeRoomPda] = deriveRoom(edgeMint, edgeCreator.publicKey, programId);
      [edgeEscrowPda] = deriveEscrow(edgeRoomPda, programId);
      [lonelyBetPda] = deriveBet(edgeRoomPda, lonelyBettor.publicKey, "moon", programId);
    });

    it("room with bets only on one side settles correctly", async function () {
      this.timeout(400_000);

      await program.methods
        .createRoom(edgeMint, "LONELY", 10, null, null, 0)
        .accounts({
          room: edgeRoomPda,
          escrow: edgeEscrowPda,
          creator: edgeCreator.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([edgeCreator])
        .rpc();

      // Only one bettor on Moon side
      await program.methods
        .placeBet({ moon: {} }, new BN(LAMPORTS_PER_SOL))
        .accounts({
          room: edgeRoomPda,
          escrow: edgeEscrowPda,
          bet: lonelyBetPda,
          user: lonelyBettor.publicKey,
          reputation: null as any,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([lonelyBettor])
        .rpc();

      // Wait for expiry
      const edgeRoom = await program.account.room.fetch(edgeRoomPda);
      const now = Math.floor(Date.now() / 1000);
      const waitMs = (edgeRoom.expiryTimestamp.toNumber() - now + 2) * 1000;
      if (waitMs > 0) {
        console.log(`  Waiting ${Math.ceil(waitMs / 1000)}s...`);
        await new Promise((r) => setTimeout(r, waitMs));
      }

      // Moon wins (price went up)
      await program.methods
        .settleRoom(new BN(2_000_000_000))
        .accounts({
          room: edgeRoomPda,
          escrow: edgeEscrowPda,
          treasury: treasury.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          keeper: keeper.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([keeper])
        .rpc();

      const settled = await program.account.room.fetch(edgeRoomPda);
      assert.deepEqual(settled.winner, { moon: {} });

      // Lonely bettor claims — gets full pot minus fee
      await program.methods
        .claimWinnings()
        .accounts({
          room: edgeRoomPda,
          config: configPda,
          escrow: edgeEscrowPda,
          bet: lonelyBetPda,
          user: lonelyBettor.publicKey,
          payer: lonelyBettor.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([lonelyBettor])
        .rpc();

      const bet = await program.account.bet.fetch(lonelyBetPda);
      assert.isTrue(bet.claimed);
      console.log("  Lonely winner claimed successfully — full pot minus fee.");
    });
  });

  describe("limit orders", () => {
    const limitMint = Keypair.generate().publicKey;
    const limitCreator = Keypair.generate();
    const bettor = Keypair.generate();
    const relayer = Keypair.generate();
    
    let limitRoomPda: PublicKey;
    let limitEscrowPda: PublicKey;
    let orderPda0: PublicKey;
    let orderPda1: PublicKey;
    let betPda: PublicKey;

    before(async () => {
      await Promise.all([
        airdrop(provider, limitCreator.publicKey, 5),
        airdrop(provider, bettor.publicKey, 10),
        airdrop(provider, relayer.publicKey, 2),
      ]);

      [limitRoomPda] = deriveRoom(limitMint, limitCreator.publicKey, programId);
      [limitEscrowPda] = deriveEscrow(limitRoomPda, programId);
      [orderPda0] = deriveLimitOrder(bettor.publicKey, limitRoomPda, 0, programId);
      [orderPda1] = deriveLimitOrder(bettor.publicKey, limitRoomPda, 1, programId);
      [betPda] = deriveBet(limitRoomPda, bettor.publicKey, "moon", programId);
    });

    it("creates a room for limit order betting", async () => {
      await program.methods
        .createRoom(limitMint, "LIMITOK", 30, null, null, 0)
        .accounts({
          room: limitRoomPda,
          escrow: limitEscrowPda,
          creator: limitCreator.publicKey,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          switchboardFeed: PublicKey.default,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([limitCreator])
        .rpc();
      
      const r = await program.account.room.fetch(limitRoomPda);
      assert.deepEqual(r.status, { active: {} });
    });

    it("queues and funds a secure escrow-based limit order", async () => {
      const orderAmount = new BN(1.5 * LAMPORTS_PER_SOL);
      const limitPrice = new BN(160_000_000); // Trigger when <= $160.00
      
      await program.methods
        .createLimitOrder(
          { moon: {} },
          orderAmount,
          limitPrice,
          0, // trigger_direction: 0 (below)
          0, // nonce
          50 // max_slippage_bps
        )
        .accounts({
          limitOrder: orderPda0,
          room: limitRoomPda,
          user: bettor.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([bettor])
        .rpc();

      const order = await program.account.limitOrder.fetch(orderPda0);
      assert.equal(order.user.toBase58(), bettor.publicKey.toBase58());
      assert.equal(order.room.toBase58(), limitRoomPda.toBase58());
      assert.deepEqual(order.side, { moon: {} });
      assert.isTrue(order.amount.eq(orderAmount));
      assert.isTrue(order.limitPrice.eq(limitPrice));
      assert.equal(order.triggerDirection, 0);
      assert.equal(order.nonce, 0);
      assert.equal(order.status, 0); // Pending

      // Verify the limit order PDA is funded
      const orderBal = await provider.connection.getBalance(orderPda0);
      assert.isAtLeast(orderBal, orderAmount.toNumber());
    });

    it("cancels a limit order and refunds 100% of escrowed SOL", async () => {
      const orderAmount = new BN(1 * LAMPORTS_PER_SOL);
      const limitPrice = new BN(160_000_000);
      
      // 1. Create order 1
      await program.methods
        .createLimitOrder(
          { moon: {} },
          orderAmount,
          limitPrice,
          0,
          1, // nonce: 1
          50
        )
        .accounts({
          limitOrder: orderPda1,
          room: limitRoomPda,
          user: bettor.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([bettor])
        .rpc();

      const userBefore = await provider.connection.getBalance(bettor.publicKey);

      // 2. Cancel order 1
      await program.methods
        .cancelLimitOrder()
        .accounts({
          limitOrder: orderPda1,
          room: limitRoomPda,
          user: bettor.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .signers([bettor])
        .rpc();

      const order = await program.account.limitOrder.fetch(orderPda1);
      assert.equal(order.status, 2); // Cancelled

      const userAfter = await provider.connection.getBalance(bettor.publicKey);
      // User got refunded, so balance should be back minus a tiny gas fee
      assert.isAbove(userAfter - userBefore, 0.99 * LAMPORTS_PER_SOL);
    });

    it("executes a limit order autonomously signed by a relayer", async () => {
      // Current Pyth feed mock price is $150.00, which is <= $160.00 (trigger condition met!)
      const roomBefore = await program.account.room.fetch(limitRoomPda);
      assert.isTrue(roomBefore.moonPool.eq(new BN(0)));

      await program.methods
        .executeLimitOrder()
        .accounts({
          limitOrder: orderPda0,
          room: limitRoomPda,
          escrow: limitEscrowPda,
          bet: betPda,
          priceFeed: MOCK_PRICE_FEED.publicKey,
          relayer: relayer.publicKey,
          config: configPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([relayer])
        .rpc();

      const order = await program.account.limitOrder.fetch(orderPda0);
      assert.equal(order.status, 1); // Executed

      const roomAfter = await program.account.room.fetch(limitRoomPda);
      assert.isTrue(roomAfter.moonPool.eq(order.amount));

      const bet = await program.account.bet.fetch(betPda);
      assert.isTrue(bet.amount.eq(order.amount));
    });
  });
});
