/**
 * eventListener.ts
 *
 * Subscribes to the ShitMarket Solana program's logs via `logsSubscribe`,
 * decodes Anchor events, and fans out to DB + Redis for each event type.
 *
 * Idempotency: every transaction signature is checked against Redis before
 * processing to handle reconnects and rare duplicate deliveries.
 *
 * Phase 3.3: Added PlatformPaused event handler.
 * Phase 3.5: Added ReputationUpdated event handler.
 * Phase 3.2: RoomSettled now includes twapFinalPrice.
 */

import {
  Connection,
  PublicKey,
  Logs,
  Keypair,
} from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import axios from 'axios';
import bs58 from 'bs58';

import { config } from '../config';
import { logger } from '../logger';
import { prisma } from '../db';
import { redis } from '../redis';

let activeConnection: Connection | null = null;
let activeProgram: anchor.Program | null = null;
let keeperKeypair: Keypair | null = null;

interface EventListenerStatus {
  isRunning: boolean;
  lastEventReceivedAt: string | null;
  lastEventProcessedAt: string | null;
  lastError: string | null;
}

const eventListenerStatus: EventListenerStatus = {
  isRunning: false,
  lastEventReceivedAt: null,
  lastEventProcessedAt: null,
  lastError: null,
};

export function getEventListenerStatus(): EventListenerStatus {
  return { ...eventListenerStatus };
}

function getKeeperKeypair(): Keypair {
  if (keeperKeypair) return keeperKeypair;
  const raw = config.solana.keeperPrivateKey;
  try {
    if (raw.startsWith('[')) {
      const arr: number[] = JSON.parse(raw);
      keeperKeypair = Keypair.fromSecretKey(Uint8Array.from(arr));
    } else {
      keeperKeypair = Keypair.fromSecretKey(new Uint8Array(bs58.decode(raw)));
    }
    return keeperKeypair;
  } catch (err) {
    throw new Error(`Invalid KEEPER_PRIVATE_KEY format in eventListener: ${err}`);
  }
}

function getProgram(connection: Connection): anchor.Program {
  if (activeProgram) return activeProgram;
  
  const programId = new PublicKey(config.solana.programId);
  let idl: any;
  try {
    idl = require('../../../program/target/idl/shitmarket.json');
  } catch {
    try {
      idl = require('../utils/idl.json');
    } catch {
      try {
        idl = require('../utils/idl.json');
      } catch {
        throw new Error('Failed to load IDL in eventListener');
      }
    }
  }

  const wallet = new anchor.Wallet(anchor.web3.Keypair.generate());
  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
  });
  
  const idlWithAddress = { ...idl, address: programId.toBase58() };
  
  function normalizeIdl(obj: any): void {
    if (Array.isArray(obj)) {
      obj.forEach(normalizeIdl);
    } else if (obj !== null && typeof obj === 'object') {
      for (const key in obj) {
        if (key === 'defined' && typeof obj[key] === 'string') {
          obj[key] = { name: obj[key] };
        } else {
          normalizeIdl(obj[key]);
        }
      }
    }
  }
  normalizeIdl(idlWithAddress);
  
  activeProgram = new anchor.Program(idlWithAddress as anchor.Idl, provider);
  return activeProgram;
}
import {
  cacheRoom,
  getCachedRoom,
  publishRoomUpdate,
  isAlreadyProcessed,
  markProcessed,
  updateLeaderboard,
} from '../redis';
import {
  roomsCreatedTotal,
  roomsSettledTotal,
  betsPlacedTotal,
  betsVolumeTotal,
  activeRoomsGauge,
  eventProcessingDuration,
} from '../metrics/prometheus';


// ─── Anchor IDL shim ──────────────────────────────────────────────────────────
// The real IDL is generated by `anchor build`. We define the event shapes
// manually here so the indexer compiles without requiring the Rust build.

interface RoomCreatedEvent {
  room: anchor.web3.PublicKey;
  creator: anchor.web3.PublicKey;
  tokenMint: anchor.web3.PublicKey;
  tokenName: string;
  priceFeed: anchor.web3.PublicKey;
  openingPrice: anchor.BN;
  durationMinutes: number;
  expiryTimestamp: anchor.BN;
  oracle: anchor.web3.PublicKey;
  oracleFeeLamports: anchor.BN;
  resolutionCriteria: number[];
}

interface RoomDisputedEvent {
  room: anchor.web3.PublicKey;
  challenger: anchor.web3.PublicKey;
  disputeBond: anchor.BN;
}

interface DisputeResolvedEvent {
  room: anchor.web3.PublicKey;
  winner: number;
  refundChallenger: boolean;
}



interface BetPlacedEvent {
  room: anchor.web3.PublicKey;
  user: anchor.web3.PublicKey;
  side: number; // 0 = Moon, 1 = Jeet
  amount: anchor.BN;
  moonPool: anchor.BN;
  jeetPool: anchor.BN;
}

interface RoomSettledEvent {
  room: anchor.web3.PublicKey;
  winner: number; // 0 = Moon, 1 = Jeet
  openingPrice: anchor.BN;
  finalPrice: anchor.BN;
  twapFinalPrice: anchor.BN;
  totalPool: anchor.BN;
  platformFee: anchor.BN;
}

interface WingsClaimedEvent {
  room: anchor.web3.PublicKey;
  user: anchor.web3.PublicKey;
  amount: anchor.BN;
}

interface PlatformPausedEvent {
  paused: boolean;
}

interface ReputationUpdatedEvent {
  user: anchor.web3.PublicKey;
  tier: number; // 0=D, 1=C, 2=B, 3=A, 4=S
  totalBets: anchor.BN;
  totalWins: anchor.BN;
}

interface RoomVoidedEvent {
  room: anchor.web3.PublicKey;
  totalRefundPool: anchor.BN;
  reason: string;
}

interface ReferralRegisteredEvent {
  user: anchor.web3.PublicKey;
  referrer: anchor.web3.PublicKey;
}

interface ReferralRewardAccruedEvent {
  referrer: anchor.web3.PublicKey;
  invitee: anchor.web3.PublicKey;
  room: anchor.web3.PublicKey;
  rewardAmount: anchor.BN;
}

interface ReferralRewardsClaimedEvent {
  referrer: anchor.web3.PublicKey;
  amount: anchor.BN;
}

interface PositionListedEvent {
  room: anchor.web3.PublicKey;
  bet: anchor.web3.PublicKey;
  seller: anchor.web3.PublicKey;
  price: anchor.BN;
}

interface PositionPurchasedEvent {
  room: anchor.web3.PublicKey;
  bet: anchor.web3.PublicKey;
  seller: anchor.web3.PublicKey;
  buyer: anchor.web3.PublicKey;
  price: anchor.BN;
}

interface ListingCancelledEvent {
  room: anchor.web3.PublicKey;
  bet: anchor.web3.PublicKey;
  seller: anchor.web3.PublicKey;
}

// ─── Token metadata fetch ─────────────────────────────────────────────────────

interface TokenMeta {
  name?: string;
  symbol?: string;
  imageUrl?: string;
  chainId?: string;
  originalAddress?: string;
  priceUsd?: string;
  pairAddress?: string;
}

async function fetchTokenMeta(mintAddress: string): Promise<TokenMeta> {
  try {
    const cached = await redis.get(`tokenmeta:${mintAddress}`);
    if (cached) {
      return JSON.parse(cached);
    }

    let lookupAddress = mintAddress;
    let isEvm = false;
    try {
      const pubkey = new PublicKey(mintAddress);
      const buffer = pubkey.toBuffer();
      let evmCheck = true;
      for (let i = 20; i < 32; i++) {
        if (buffer[i] !== 0) {
          evmCheck = false;
          break;
        }
      }
      if (evmCheck) {
        lookupAddress = '0x' + buffer.slice(0, 20).toString('hex');
        isEvm = true;
      }
    } catch {
      if (mintAddress.startsWith('0x')) {
        isEvm = true;
      }
    }

    const url = `${config.external.dexscreenerUrl}/tokens/${lookupAddress}`;
    const { data } = await axios.get(url, { timeout: 5000 });
    const pairs: any[] = data?.pairs ?? [];
    if (!pairs.length) return {};
    const best = pairs.sort((a, b) => (b.liquidity?.usd ?? 0) - (a.liquidity?.usd ?? 0))[0];
    
    const meta: TokenMeta = {
      name: best.baseToken?.name,
      symbol: best.baseToken?.symbol,
      imageUrl: best.info?.imageUrl ?? undefined,
      chainId: best.chainId ?? (isEvm ? 'monad' : 'solana'),
      originalAddress: lookupAddress,
      priceUsd: best.priceUsd ? best.priceUsd : undefined,
      pairAddress: best.pairAddress,
    };

    await redis.set(`tokenmeta:${mintAddress}`, JSON.stringify(meta), 'EX', 86400); // 24 hour cache
    return meta;
  } catch (err: any) {
    logger.warn({ msg: 'fetchTokenMeta failed', mintAddress, err: err?.message });
    return {};
  }
}

// ─── Event handlers ───────────────────────────────────────────────────────────

async function handleRoomCreated(event: RoomCreatedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'RoomCreated' });
  try {
    const roomPubkey = event.room.toBase58();
    const tokenMint = event.tokenMint.toBase58();
    const expiry = new Date(event.expiryTimestamp.toNumber() * 1000);

    const meta = await fetchTokenMeta(tokenMint);
    const openingPrice = BigInt(event.openingPrice.toString());

    const statusVal = 'active';

    const criteriaBuf = Buffer.from(event.resolutionCriteria || []);
    const nullIdx = criteriaBuf.indexOf(0);
    const criteriaStr = criteriaBuf.toString('utf8', 0, nullIdx === -1 ? criteriaBuf.length : nullIdx).trim();

    await prisma.room.upsert({
      where: { roomPubkey },
      create: {
        roomPubkey,
        tokenMint,
        priceFeed: event.priceFeed.toBase58(),
        tokenName: meta.name ?? event.tokenName,
        tokenSymbol: meta.symbol,
        tokenImageUrl: meta.imageUrl,
        chainId: meta.chainId ?? 'solana',
        originalAddress: meta.originalAddress ?? tokenMint,
        duration: event.durationMinutes,
        openingPrice,
        expiry,
        status: statusVal,
        creator: event.creator.toBase58(),
        oracleAddress: event.oracle.toBase58(),
        oracleFeeLamports: BigInt(event.oracleFeeLamports.toString()),
        resolutionCriteria: criteriaStr,
      },
      update: {
        priceFeed: event.priceFeed.toBase58(),
        creator: event.creator.toBase58(),
        tokenName: meta.name ?? event.tokenName,
        tokenSymbol: meta.symbol,
        tokenImageUrl: meta.imageUrl,
        chainId: meta.chainId ?? 'solana',
        originalAddress: meta.originalAddress ?? tokenMint,
        oracleAddress: event.oracle.toBase58(),
        oracleFeeLamports: BigInt(event.oracleFeeLamports.toString()),
        resolutionCriteria: criteriaStr,
      },
    });

    await cacheRoom(roomPubkey, {
      status: statusVal,
      tokenMint,
      tokenName: meta.name ?? event.tokenName,
      tokenSymbol: meta.symbol ?? '',
      tokenImageUrl: meta.imageUrl ?? '',
      openingPrice: openingPrice.toString(),
      moonPool: '0',
      jeetPool: '0',
      expiry: expiry.toISOString(),
      pairAddress: meta.pairAddress ?? '',
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomCreated',
      tokenName: meta.name ?? event.tokenName,
      tokenSymbol: meta.symbol,
      tokenImageUrl: meta.imageUrl,
      chainId: meta.chainId ?? 'solana',
      originalAddress: meta.originalAddress ?? tokenMint,
      expiry: expiry.toISOString(),
    });

    roomsCreatedTotal.inc();

    // Update active room gauge
    const activeCount = await prisma.room.count({ where: { status: 'active' } });
    activeRoomsGauge.set(activeCount);

    logger.info({ msg: 'RoomCreated processed', roomPubkey, tokenMint, openingPrice: openingPrice.toString() });
  } finally {
    end();
  }
}

async function handleBetPlaced(event: BetPlacedEvent, signature?: string): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'BetPlaced' });
  try {
    const roomPubkey = event.room.toBase58();
    const userPubkey = event.user.toBase58();
    const side = event.side === 0 ? 'moon' : 'jeet';
    const amount = BigInt(event.amount.toString());

    // Upsert bet — same user+room+side increments amount
    const existing = await prisma.bet.findFirst({
      where: { roomPubkey, userPubkey, side },
    });

    if (existing) {
      await prisma.bet.update({
        where: { id: existing.id },
        data: { amount: existing.amount + amount, txSig: signature || existing.txSig },
      });
    } else {
      await prisma.bet.create({
        data: { roomPubkey, userPubkey, side, amount, txSig: signature },
      });
    }

    // Update room pool totals in DB
    await prisma.room.update({
      where: { roomPubkey },
      data: {
        totalPool: {
          increment: amount,
        },
      },
    });

    // Update Redis cache
    const moonPool = event.moonPool.toString();
    const jeetPool = event.jeetPool.toString();
    await cacheRoom(roomPubkey, { moonPool, jeetPool });

    await publishRoomUpdate(roomPubkey, {
      type: 'BetPlaced',
      user: userPubkey,
      side,
      amount: amount.toString(),
      moonPool,
      jeetPool,
    });

    // Upsert user profile
    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: { userPubkey, totalBets: 1 },
      update: { totalBets: { increment: 1 } },
    });

    betsPlacedTotal.inc({ side });
    betsVolumeTotal.inc(Number(amount));

    logger.info({ msg: 'BetPlaced processed', roomPubkey, userPubkey, side, amount: amount.toString() });
  } finally {
    end();
  }
}



async function handleRoomSettled(event: RoomSettledEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'RoomSettled' });
  try {
    const roomPubkey = event.room.toBase58();

    const isDraw = event.winner === 2;
    const winner = isDraw ? 'draw' : (event.winner === 0 ? 'moon' : 'jeet');
    const finalPrice = BigInt(event.finalPrice.toString());
    const twapFinalPrice = BigInt(event.twapFinalPrice.toString());

    logger.info({
      msg: 'Processing RoomSettled event with direct on-chain values',
      roomPubkey,
      winner,
      finalPrice: finalPrice.toString(),
      twapFinalPrice: twapFinalPrice.toString()
    });

    const totalPool = BigInt(event.totalPool.toString());
    const platformFee = BigInt(event.platformFee.toString());
    const payoutPool = totalPool - platformFee;

    // Fetch winning bets: in a draw, all bets are "winning" bets to receive refunds proportionally
    const winningBets = isDraw 
      ? await prisma.bet.findMany({ where: { roomPubkey } })
      : await prisma.bet.findMany({ where: { roomPubkey, side: winner } });

    const winningPool = isDraw ? totalPool : winningBets.reduce((sum, b) => sum + b.amount, BigInt(0));

    // Compute and store individual payouts in a transaction-ready format
    const payoutOps = [];
    for (const bet of winningBets) {
      if (winningPool === BigInt(0)) continue;
      const payout = (bet.amount * payoutPool) / winningPool;

      payoutOps.push(
        prisma.payout.upsert({
          where: {
            roomPubkey_userPubkey: {
              roomPubkey,
              userPubkey: bet.userPubkey,
            },
          },
          create: {
            roomPubkey,
            userPubkey: bet.userPubkey,
            amount: payout,
          },
          update: {
            amount: payout,
          },
        })
      );
    }

    // Update losers' stats (none in a Draw!)
    const losingBets = isDraw 
      ? [] 
      : await prisma.bet.findMany({ where: { roomPubkey, side: winner === 'moon' ? 'jeet' : 'moon' } });

    const loserOps = losingBets.map(bet =>
      prisma.userProfile.upsert({
        where: { userPubkey: bet.userPubkey },
        create: {
          userPubkey: bet.userPubkey,
          losses: 1,
          profit: -bet.amount,
        },
        update: {
          losses: { increment: 1 },
          profit: { decrement: bet.amount },
        },
      })
    );

    // Run loser leaderboard updates in parallel via Redis
    await Promise.all(losingBets.map(bet => updateLeaderboard(bet.userPubkey, -bet.amount)));

    // Mark room settled in DB (including twapFinalPrice)
    const roomUpdateOp = prisma.room.update({
      where: { roomPubkey },
      data: {
        status: 'settled',
        winner,
        finalPrice,
        twapFinalPrice,
        platformFee,
        settledAt: new Date(),
      },
    });

    // Execute all database updates atomically inside a transaction
    await prisma.$transaction([
      ...payoutOps,
      ...loserOps,
      roomUpdateOp,
    ]);

    // Update Redis cache
    await cacheRoom(roomPubkey, {
      status: 'settled',
      winner,
      finalPrice: finalPrice.toString(),
      twapFinalPrice: twapFinalPrice.toString(),
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomSettled',
      winner,
      finalPrice: finalPrice.toString(),
      twapFinalPrice: twapFinalPrice.toString(),
      totalPool: totalPool.toString(),
      platformFee: platformFee.toString(),
    });

    roomsSettledTotal.inc({ winner });

    const activeCount = await prisma.room.count({ where: { status: 'active' } });
    activeRoomsGauge.set(activeCount);

    logger.info({ msg: 'RoomSettled processed', roomPubkey, winner, finalPrice: finalPrice.toString(), twapFinalPrice: twapFinalPrice.toString() });

    // ═══════════════════════════════════════════════════════════════
    // Automatic payouts REMOVED — users must manually claim their
    // winnings/refunds via the frontend "Claim" button.
    //
    // Reasoning:
    // 1. Prevents escrow drain from race conditions (keeper auto-claim
    //    + user manual claim both attempting to pay the same bet).
    // 2. Saves compute units and RPC costs for the keeper.
    // 3. Avoids issues where the keeper lacks the correct referral
    //    accounts to pass as remaining_accounts to claimWinnings.
    // 4. Users get a better UX by claiming on their own terms.
    // ═══════════════════════════════════════════════════════════════

    // ─── Automatic Referral Payouts (0.1% reward) ───
    if (activeConnection) {
      try {
        const keeper = getKeeperKeypair();
        const roomBets = await prisma.bet.findMany({
          where: { roomPubkey },
        });

        const referralIxs: anchor.web3.TransactionInstruction[] = [];
        const referralPayoutData: { referrer: string; invitee: string; betAmount: bigint; rewardAmount: bigint }[] = [];

        // Batch fetch all bettor profiles in a single query to prevent N+1 queries in loops
        const bettorPubkeys = Array.from(new Set(roomBets.map(b => b.userPubkey)));
        const profiles = await prisma.userProfile.findMany({
          where: { userPubkey: { in: bettorPubkeys } },
          select: { userPubkey: true, referredBy: true }
        });
        const referralMap = new Map<string, string>();
        for (const p of profiles) {
          if (p.referredBy) {
            referralMap.set(p.userPubkey, p.referredBy);
          }
        }

        for (const bet of roomBets) {
          const referredBy = referralMap.get(bet.userPubkey);

          if (referredBy) {
            const referrerWallet = new PublicKey(referredBy);
            
            // Referrer gets 0.1% of bet amount (1/1000 of lamports)
            const betAmount = BigInt(bet.amount);
            const rewardAmount = betAmount / BigInt(1000);

            if (rewardAmount > BigInt(0)) {
              const ix = anchor.web3.SystemProgram.transfer({
                fromPubkey: keeper.publicKey,
                toPubkey: referrerWallet,
                lamports: Number(rewardAmount),
              });
              referralIxs.push(ix);
              referralPayoutData.push({
                referrer: referredBy,
                invitee: bet.userPubkey,
                betAmount,
                rewardAmount
              });
            }
          }
        }

        if (referralIxs.length > 0) {
          logger.info({ msg: 'Triggering on-chain referral payouts', count: referralIxs.length, roomPubkey });
          
          const REF_BATCH_SIZE = 10;
          for (let i = 0; i < referralIxs.length; i += REF_BATCH_SIZE) {
            const batchIxs = referralIxs.slice(i, i + REF_BATCH_SIZE);
            const batchData = referralPayoutData.slice(i, i + REF_BATCH_SIZE);

            const tx = new anchor.web3.Transaction();
            tx.add(...batchIxs);

            const txSig = await anchor.web3.sendAndConfirmTransaction(
              activeConnection,
              tx,
              [keeper],
              { commitment: 'confirmed', skipPreflight: true }
            );

            logger.info({ msg: 'Referral payout batch confirmed on-chain', txSig, count: batchIxs.length });

            // Batch database insertions using createMany
            await prisma.referralPayout.createMany({
              data: batchData.map(item => ({
                referrer: item.referrer,
                invitee: item.invitee,
                roomPubkey,
                betAmount: item.betAmount,
                rewardAmount: item.rewardAmount,
                txSig,
              }))
            });
          }
        }
      } catch (refErr: any) {
        logger.error({ msg: 'Referral payout failed', roomPubkey, err: refErr?.message || String(refErr) });
      }
    }
  } finally {
    end();
  }
}

async function handleWinningsClaimed(event: WingsClaimedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'WinningsClaimed' });
  try {
    const roomPubkey = event.room.toBase58();
    const userPubkey = event.user.toBase58();
    const amount = BigInt(event.amount.toString());

    // Mark bet as claimed
    await prisma.bet.updateMany({
      where: { roomPubkey, userPubkey },
      data: { claimed: true },
    });

    // Mark payout as claimed
    await prisma.payout.updateMany({
      where: { roomPubkey, userPubkey },
      data: { claimedAt: new Date() },
    });

    // Update user profile: wins + profit
    // Sum ALL bets for this user in this room (supports multi-bet per user)
    const userBets = await prisma.bet.findMany({
      where: { roomPubkey, userPubkey },
    });
    const totalBetAmount = userBets.reduce((sum, b) => sum + b.amount, BigInt(0));
    const profitGain = totalBetAmount > BigInt(0) ? amount - totalBetAmount : amount;

    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        wins: 1,
        profit: profitGain,
      },
      update: {
        wins: { increment: 1 },
        profit: { increment: profitGain },
      },
    });

    await updateLeaderboard(userPubkey, profitGain);

    await publishRoomUpdate(roomPubkey, {
      type: 'WinningsClaimed',
      user: userPubkey,
      amount: amount.toString(),
    });

    logger.info({ msg: 'WinningsClaimed processed', roomPubkey, userPubkey, amount: amount.toString() });
  } finally {
    end();
  }
}

/**
 * Phase 3.3: Handle PlatformPaused event.
 */
async function handlePlatformPaused(event: PlatformPausedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'PlatformPaused' });
  try {
    const status = event.paused ? 'paused' : 'active';
    logger.info({ msg: `Platform ${status}`, paused: event.paused });

    // Broadcast to all connected WebSocket clients
    await publishRoomUpdate('__platform__', {
      type: 'PlatformPaused',
      paused: event.paused,
    });
  } finally {
    end();
  }
}

/**
 * Phase 3.5: Handle ReputationUpdated event.
 */
async function handleReputationUpdated(event: ReputationUpdatedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'ReputationUpdated' });
  try {
    const userPubkey = event.user.toBase58();
    const tierMap = ['D', 'C', 'B', 'A', 'S'];
    const tier = tierMap[event.tier] ?? 'D';
    const totalBets = BigInt(event.totalBets.toString());
    const totalWins = BigInt(event.totalWins.toString());

    // Upsert reputation record
    await prisma.reputation.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        tier,
        totalBets,
        totalWins,
      },
      update: {
        tier,
        totalBets,
        totalWins,
        lastEval: new Date(),
      },
    });

    // Also update the user profile with the tier
    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        trenchScore: tier,
      },
      update: {
        trenchScore: tier,
      },
    });

    logger.info({
      msg: 'ReputationUpdated processed',
      userPubkey,
      tier,
      totalBets: totalBets.toString(),
      totalWins: totalWins.toString(),
    });

    await publishRoomUpdate('__reputation__', {
      type: 'ReputationUpdated',
      user: userPubkey,
      tier,
    });
  } finally {
    end();
  }
}

async function handleRoomVoided(event: RoomVoidedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'RoomVoided' });
  try {
    const roomPubkey = event.room.toBase58();

    logger.info({
      msg: 'Processing RoomVoided event (one-sided void)',
      roomPubkey,
      reason: event.reason,
    });

    const totalPool = BigInt(event.totalRefundPool.toString());
    const platformFee = BigInt(0);

    // In a voided room, everyone wins (i.e. receives full refund)
    const winningBets = await prisma.bet.findMany({ where: { roomPubkey } });

    // Compute and store individual payouts (100% refund of bet amount) inside a transaction-ready format
    const payoutOps = [];
    for (const bet of winningBets) {
      const payout = bet.amount;
      payoutOps.push(
        prisma.payout.upsert({
          where: {
            roomPubkey_userPubkey: {
              roomPubkey,
              userPubkey: bet.userPubkey,
            },
          },
          create: {
            roomPubkey,
            userPubkey: bet.userPubkey,
            amount: payout,
          },
          update: {
            amount: payout,
          },
        })
      );
    }

    // Mark room settled in DB as draw (representing void refund path)
    const roomUpdateOp = prisma.room.update({
      where: { roomPubkey },
      data: {
        status: 'settled',
        winner: 'draw',
        platformFee,
      },
    });

    // Execute database updates inside a transaction
    await prisma.$transaction([
      ...payoutOps,
      roomUpdateOp,
    ]);

    // Update Redis cache
    await cacheRoom(roomPubkey, {
      status: 'settled',
      winner: 'draw',
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomSettled',
      winner: 'draw',
      totalPool: totalPool.toString(),
      platformFee: platformFee.toString(),
    });

    roomsSettledTotal.inc({ winner: 'draw' });

    const activeCount = await prisma.room.count({ where: { status: 'active' } });
    activeRoomsGauge.set(activeCount);

    logger.info({ msg: 'RoomVoided processed successfully', roomPubkey });

    // ═══════════════════════════════════════════════════════════════
    // Automatic void refund payouts REMOVED — users must manually
    // claim their void refunds via the frontend "Claim" button.
    //
    // Reasoning is the same as for RoomSettled auto-payouts:
    // prevents escrow drain from race conditions and avoids
    // referral account issues when the keeper claims on behalf
    // of users.
    // ═══════════════════════════════════════════════════════════════
  } finally {
    end();
  }
}

async function handleReferralRegistered(event: ReferralRegisteredEvent): Promise<void> {
  try {
    const userPubkey = event.user.toBase58();
    const referrerPubkey = event.referrer.toBase58();

    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: { userPubkey, referredBy: referrerPubkey },
      update: { referredBy: referrerPubkey },
    });

    logger.info({ msg: 'ReferralRegistered processed', userPubkey, referrerPubkey });
  } catch (err: any) {
    logger.error({ msg: 'ReferralRegistered failed', err: err.message });
  }
}

async function handleReferralRewardAccrued(event: ReferralRewardAccruedEvent, signature?: string): Promise<void> {
  try {
    const referrer = event.referrer.toBase58();
    const invitee = event.invitee.toBase58();
    const roomPubkey = event.room.toBase58();
    const rewardAmount = BigInt(event.rewardAmount.toString());

    const bet = await prisma.bet.findFirst({
      where: { roomPubkey, userPubkey: invitee },
    });
    const betAmount = bet ? bet.amount : BigInt(0);

    await prisma.referralPayout.create({
      data: {
        referrer,
        invitee,
        roomPubkey,
        betAmount,
        rewardAmount,
        txSig: signature,
      },
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'ReferralRewardAccrued',
      referrer,
      invitee,
      rewardAmount: rewardAmount.toString(),
    });

    logger.info({ msg: 'ReferralRewardAccrued processed', referrer, invitee, rewardAmount: rewardAmount.toString() });
  } catch (err: any) {
    logger.error({ msg: 'ReferralRewardAccrued failed', err: err.message });
  }
}

async function handleReferralRewardsClaimed(event: ReferralRewardsClaimedEvent, signature?: string): Promise<void> {
  try {
    const referrer = event.referrer.toBase58();
    const amount = BigInt(event.amount.toString());

    await publishRoomUpdate('__referrals__', {
      type: 'ReferralRewardsClaimed',
      referrer,
      amount: amount.toString(),
      txSig: signature,
    });

    logger.info({ msg: 'ReferralRewardsClaimed processed', referrer, amount: amount.toString() });
  } catch (err: any) {
    logger.error({ msg: 'ReferralRewardsClaimed failed', err: err.message });
  }
}

async function handlePositionListed(event: PositionListedEvent): Promise<void> {
  try {
    const roomPubkey = event.room.toBase58();
    const sellerPubkey = event.seller.toBase58();
    const price = BigInt(event.price.toString());

    await prisma.activity.create({
      data: {
        userPubkey: sellerPubkey,
        type: 'bet',
        title: 'POSITION LISTED',
        message: `You listed your position in room ${roomPubkey.substring(0, 4)} for ${(Number(price) / 1e9).toFixed(4)} SOL.`,
        link: `/room/${roomPubkey}`
      }
    });

    logger.info({ msg: 'PositionListed processed', room: roomPubkey, seller: sellerPubkey, price: price.toString() });
  } catch (err: any) {
    logger.error({ msg: 'PositionListed failed', err: err.message });
  }
}

async function handlePositionPurchased(event: PositionPurchasedEvent): Promise<void> {
  try {
    const roomPubkey = event.room.toBase58();
    const sellerPubkey = event.seller.toBase58();
    const buyerPubkey = event.buyer.toBase58();
    const price = BigInt(event.price.toString());

    const bet = await prisma.bet.findFirst({
      where: { roomPubkey, userPubkey: sellerPubkey, claimed: false }
    });

    if (bet) {
      const existingBuyerBet = await prisma.bet.findFirst({
        where: { roomPubkey, userPubkey: buyerPubkey, side: bet.side, claimed: false }
      });

      if (existingBuyerBet) {
        await prisma.$transaction([
          prisma.bet.update({
            where: { id: existingBuyerBet.id },
            data: { amount: existingBuyerBet.amount + bet.amount }
          }),
          prisma.bet.delete({
            where: { id: bet.id }
          })
        ]);
      } else {
        await prisma.bet.update({
          where: { id: bet.id },
          data: { userPubkey: buyerPubkey }
        });
      }

      await prisma.userProfile.upsert({
        where: { userPubkey: buyerPubkey },
        create: { userPubkey: buyerPubkey, totalBets: 1 },
        update: { totalBets: { increment: 1 } }
      });

      await prisma.activity.createMany({
        data: [
          {
            userPubkey: sellerPubkey,
            type: 'settlement',
            title: 'POSITION SOLD',
            message: `Your position in room ${roomPubkey.substring(0, 4)} was sold for ${(Number(price) / 1e9).toFixed(4)} SOL.`,
            link: `/room/${roomPubkey}`
          },
          {
            userPubkey: buyerPubkey,
            type: 'bet',
            title: 'POSITION ACQUIRED',
            message: `You acquired a position in room ${roomPubkey.substring(0, 4)} for ${(Number(price) / 1e9).toFixed(4)} SOL.`,
            link: `/room/${roomPubkey}`
          }
        ]
      });

      await publishRoomUpdate(roomPubkey, {
        type: 'PositionPurchased',
        seller: sellerPubkey,
        buyer: buyerPubkey,
        price: price.toString()
      });
    }

    logger.info({ msg: 'PositionPurchased processed', room: roomPubkey, seller: sellerPubkey, buyer: buyerPubkey, price: price.toString() });
  } catch (err: any) {
    logger.error({ msg: 'PositionPurchased failed', err: err.message });
  }
}

async function handleListingCancelled(event: ListingCancelledEvent): Promise<void> {
  try {
    const roomPubkey = event.room.toBase58();
    const sellerPubkey = event.seller.toBase58();

    await prisma.activity.create({
      data: {
        userPubkey: sellerPubkey,
        type: 'bet',
        title: 'LISTING CANCELLED',
        message: `You cancelled your position listing in room ${roomPubkey.substring(0, 4)}.`,
        link: `/room/${roomPubkey}`
      }
    });

    logger.info({ msg: 'ListingCancelled processed', room: roomPubkey, seller: sellerPubkey });
  } catch (err: any) {
    logger.error({ msg: 'ListingCancelled failed', err: err.message });
  }
}

async function handleRoomDisputed(event: RoomDisputedEvent): Promise<void> {
  try {
    const roomPubkey = event.room.toBase58();
    const challenger = event.challenger.toBase58();
    const disputeBond = BigInt(event.disputeBond.toString());

    await prisma.room.update({
      where: { roomPubkey },
      data: {
        status: 'disputed',
        disputedAt: new Date(),
        disputeChallenger: challenger,
        disputeBond: disputeBond,
      },
    });

    await cacheRoom(roomPubkey, {
      status: 'disputed',
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomDisputed',
      challenger,
      disputeBond: disputeBond.toString(),
    });

    logger.info({ msg: 'RoomDisputed processed', roomPubkey, challenger });
  } catch (err: any) {
    logger.error({ msg: 'RoomDisputed failed', err: err.message });
  }
}

async function handleDisputeResolved(event: DisputeResolvedEvent): Promise<void> {
  try {
    const roomPubkey = event.room.toBase58();
    const isDraw = event.winner === 2;
    const winner = isDraw ? 'draw' : (event.winner === 0 ? 'moon' : 'jeet');
    const overturned = event.refundChallenger;

    const room = await prisma.room.findUnique({
      where: { roomPubkey },
      include: { bets: true },
    });

    if (!room) return;

    const totalPool = room.totalPool;
    const platformFee = room.platformFee;
    const oracleFee = room.oracleFeeLamports;
    const payoutPool = totalPool - platformFee - oracleFee;

    // Clear existing payouts so we can write the new resolved payouts
    await prisma.payout.deleteMany({ where: { roomPubkey } });

    const winningBets = isDraw 
      ? room.bets 
      : room.bets.filter(b => b.side === winner);

    const winningPool = isDraw ? totalPool : winningBets.reduce((sum, b) => sum + b.amount, BigInt(0));

    const payoutOps = [];
    for (const bet of winningBets) {
      if (winningPool === BigInt(0)) continue;
      const payout = (bet.amount * payoutPool) / winningPool;

      payoutOps.push(
        prisma.payout.create({
          data: {
            roomPubkey,
            userPubkey: bet.userPubkey,
            amount: payout,
          },
        })
      );
    }

    const roomUpdate = prisma.room.update({
      where: { roomPubkey },
      data: {
        status: 'settled',
        winner,
        disputeStatus: overturned ? 1 : 0,
      },
    });

    await prisma.$transaction([
      roomUpdate,
      ...payoutOps
    ]);

    await cacheRoom(roomPubkey, {
      status: 'settled',
      winner,
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'DisputeResolved',
      winner,
      overturned,
    });

    logger.info({ msg: 'DisputeResolved processed', roomPubkey, winner, overturned });
  } catch (err: any) {
    logger.error({ msg: 'DisputeResolved failed', err: err.message });
  }
}

let subscriptionId: number | null = null;

export async function processParsedEvents(events: any[], signature: string): Promise<void> {
  if (await isAlreadyProcessed(signature)) {
    logger.debug({ msg: 'Duplicate tx skipped', signature });
    return;
  }

  for (const event of events) {
    logger.debug({ msg: 'Processing event', name: event.name, signature });

    switch (event.name) {
      case 'RoomCreated':
        await handleRoomCreated(event.data as RoomCreatedEvent);
        break;

      case 'BetPlaced':
        await handleBetPlaced(event.data as BetPlacedEvent, signature);
        break;
      case 'RoomSettled':
        await handleRoomSettled(event.data as RoomSettledEvent);
        break;
      case 'WinningsClaimed':
        await handleWinningsClaimed(event.data as WingsClaimedEvent);
        break;
      case 'PlatformPaused':
        await handlePlatformPaused(event.data as PlatformPausedEvent);
        break;
      case 'ReputationUpdated':
        await handleReputationUpdated(event.data as ReputationUpdatedEvent);
        break;
      case 'RoomVoided':
        await handleRoomVoided(event.data as RoomVoidedEvent);
        break;
      case 'ReferralRegistered':
        await handleReferralRegistered(event.data as ReferralRegisteredEvent);
        break;
      case 'ReferralRewardAccrued':
        await handleReferralRewardAccrued(event.data as ReferralRewardAccruedEvent, signature);
        break;
      case 'ReferralRewardsClaimed':
        await handleReferralRewardsClaimed(event.data as ReferralRewardsClaimedEvent, signature);
        break;
      case 'PositionListed':
        await handlePositionListed(event.data as PositionListedEvent);
        break;
      case 'PositionPurchased':
        await handlePositionPurchased(event.data as PositionPurchasedEvent);
        break;
      case 'ListingCancelled':
        await handleListingCancelled(event.data as ListingCancelledEvent);
        break;
      case 'RoomDisputed':
        await handleRoomDisputed(event.data as RoomDisputedEvent);
        break;
      case 'DisputeResolved':
        await handleDisputeResolved(event.data as DisputeResolvedEvent);
        break;
      default:
        logger.warn({ msg: 'Unknown event', name: event.name });
    }
  }

  await markProcessed(signature);
}

export function startEventListener(
  connection: Connection,
  eventParser: anchor.EventParser
): void {
  activeConnection = connection;
  eventListenerStatus.isRunning = true;
  const programId = new PublicKey(config.solana.programId);

  subscriptionId = connection.onLogs(
    programId,
    async (logs: Logs) => {
      const { signature, logs: logLines, err } = logs;
      eventListenerStatus.lastEventReceivedAt = new Date().toISOString();
      eventListenerStatus.lastError = null;

      if (err) {
        eventListenerStatus.lastError = String(err);
        logger.warn({ msg: 'Log with error skipped', signature, err });
        return;
      }

      // Idempotency guard
      if (await isAlreadyProcessed(signature)) {
        logger.debug({ msg: 'Duplicate tx skipped', signature });
        eventListenerStatus.lastEventProcessedAt = new Date().toISOString();
        return;
      }

      // Parse Anchor events from log lines
      try {
        const events = Array.from(eventParser.parseLogs(logLines));
        if (events.length > 0) {
          await processParsedEvents(events, signature);
        }
        eventListenerStatus.lastEventProcessedAt = new Date().toISOString();
      } catch (err: any) {
        eventListenerStatus.lastError = err?.message ?? String(err);
        logger.error({ msg: 'Event processing error', signature, err: err?.message, stack: err?.stack });
      }
    },
    'confirmed'
  );

  logger.info({ msg: 'Event listener started', programId: programId.toBase58() });
}

export async function stopEventListener(connection: Connection): Promise<void> {
  if (subscriptionId !== null) {
    await connection.removeOnLogsListener(subscriptionId);
    subscriptionId = null;
    logger.info('Event listener stopped');
  }
}
