/**
 * eventListener.ts
 *
 * Subscribes to the ShitMarket Solana program's logs via `logsSubscribe`,
 * decodes Anchor events, and fans out to DB + Redis for each event type.
 *
 * Idempotency: every transaction signature is checked against Redis before
 * processing to handle reconnects and rare duplicate deliveries.
 *
 * Phase 3.3: Added PlatformPaused event handler.
 * Phase 3.5: Added ReputationUpdated event handler.
 * Phase 3.2: RoomSettled now includes twapFinalPrice.
 */

import {
  Connection,
  PublicKey,
  Logs,
} from '@solana/web3.js';
import * as anchor from '@coral-xyz/anchor';
import axios from 'axios';

import { config } from '../config';
import { logger } from '../logger';
import { prisma } from '../db';
import { redis } from '../redis';
import {
  cacheRoom,
  publishRoomUpdate,
  isAlreadyProcessed,
  markProcessed,
  updateLeaderboard,
} from '../redis';
import {
  roomsCreatedTotal,
  roomsSettledTotal,
  betsPlacedTotal,
  betsVolumeTotal,
  activeRoomsGauge,
  eventProcessingDuration,
} from '../metrics/prometheus';

// ─── Anchor IDL shim ──────────────────────────────────────────────────────────
// The real IDL is generated by `anchor build`. We define the event shapes
// manually here so the indexer compiles without requiring the Rust build.

interface RoomCreatedEvent {
  room: anchor.web3.PublicKey;
  creator: anchor.web3.PublicKey;
  tokenMint: anchor.web3.PublicKey;
  tokenName: string;
  priceFeed: anchor.web3.PublicKey;
  openingPrice: anchor.BN;
  durationMinutes: number;
  expiryTimestamp: anchor.BN;
}

interface BetPlacedEvent {
  room: anchor.web3.PublicKey;
  user: anchor.web3.PublicKey;
  side: number; // 0 = Moon, 1 = Jeet
  amount: anchor.BN;
  moonPool: anchor.BN;
  jeetPool: anchor.BN;
}

interface RoomSettledEvent {
  room: anchor.web3.PublicKey;
  winner: number; // 0 = Moon, 1 = Jeet
  openingPrice: anchor.BN;
  finalPrice: anchor.BN;
  twapFinalPrice: anchor.BN;
  totalPool: anchor.BN;
  platformFee: anchor.BN;
}

interface WingsClaimedEvent {
  room: anchor.web3.PublicKey;
  user: anchor.web3.PublicKey;
  amount: anchor.BN;
}

interface PlatformPausedEvent {
  paused: boolean;
}

interface ReputationUpdatedEvent {
  user: anchor.web3.PublicKey;
  tier: number; // 0=D, 1=C, 2=B, 3=A, 4=S
  totalBets: anchor.BN;
  totalWins: anchor.BN;
}

// ─── Token metadata fetch ─────────────────────────────────────────────────────

interface TokenMeta {
  name?: string;
  symbol?: string;
  imageUrl?: string;
  chainId?: string;
  originalAddress?: string;
}

async function fetchTokenMeta(mintAddress: string): Promise<TokenMeta> {
  try {
    const cached = await redis.get(`tokenmeta:${mintAddress}`);
    if (cached) {
      const parsed = JSON.parse(cached);
      return {
        originalAddress: parsed.originalAddress,
        chainId: parsed.chainId,
        imageUrl: parsed.imageUrl,
      };
    }

    const url = `${config.external.dexscreenerUrl}/tokens/${mintAddress}`;
    const { data } = await axios.get(url, { timeout: 5000 });
    const pairs: any[] = data?.pairs ?? [];
    if (!pairs.length) return {};
    const best = pairs.sort((a, b) => (b.liquidity?.usd ?? 0) - (a.liquidity?.usd ?? 0))[0];
    return {
      name: best.baseToken?.name,
      symbol: best.baseToken?.symbol,
      imageUrl: best.info?.imageUrl ?? undefined,
      chainId: best.chainId ?? 'solana',
      originalAddress: mintAddress,
    };
  } catch {
    return {};
  }
}

// ─── Event handlers ───────────────────────────────────────────────────────────

async function handleRoomCreated(event: RoomCreatedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'RoomCreated' });
  try {
    const roomPubkey = event.room.toBase58();
    const tokenMint = event.tokenMint.toBase58();
    const expiry = new Date(event.expiryTimestamp.toNumber() * 1000);

    const meta = await fetchTokenMeta(tokenMint);

    await prisma.room.upsert({
      where: { roomPubkey },
      create: {
        roomPubkey,
        tokenMint,
        priceFeed: event.priceFeed.toBase58(),
        tokenName: meta.name ?? event.tokenName,
        tokenSymbol: meta.symbol,
        tokenImageUrl: meta.imageUrl,
        chainId: meta.chainId ?? 'solana',
        originalAddress: meta.originalAddress ?? tokenMint,
        duration: event.durationMinutes,
        openingPrice: BigInt(event.openingPrice.toString()),
        expiry,
        status: 'active',
      },
      update: {
        priceFeed: event.priceFeed.toBase58(),
      },
    });

    await cacheRoom(roomPubkey, {
      status: 'active',
      tokenMint,
      tokenName: meta.name ?? event.tokenName,
      tokenSymbol: meta.symbol ?? '',
      tokenImageUrl: meta.imageUrl ?? '',
      openingPrice: event.openingPrice.toString(),
      moonPool: '0',
      jeetPool: '0',
      expiry: expiry.toISOString(),
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomCreated',
      tokenName: meta.name ?? event.tokenName,
      tokenSymbol: meta.symbol,
      tokenImageUrl: meta.imageUrl,
      chainId: meta.chainId ?? 'solana',
      originalAddress: meta.originalAddress ?? tokenMint,
      expiry: expiry.toISOString(),
    });

    roomsCreatedTotal.inc();

    // Update active room gauge
    const activeCount = await prisma.room.count({ where: { status: 'active' } });
    activeRoomsGauge.set(activeCount);

    logger.info({ msg: 'RoomCreated processed', roomPubkey, tokenMint });
  } finally {
    end();
  }
}

async function handleBetPlaced(event: BetPlacedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'BetPlaced' });
  try {
    const roomPubkey = event.room.toBase58();
    const userPubkey = event.user.toBase58();
    const side = event.side === 0 ? 'moon' : 'jeet';
    const amount = BigInt(event.amount.toString());

    // Upsert bet — same user+room+side increments amount
    const existing = await prisma.bet.findFirst({
      where: { roomPubkey, userPubkey, side },
    });

    if (existing) {
      await prisma.bet.update({
        where: { id: existing.id },
        data: { amount: existing.amount + amount },
      });
    } else {
      await prisma.bet.create({
        data: { roomPubkey, userPubkey, side, amount },
      });
    }

    // Update room pool totals in DB
    await prisma.room.update({
      where: { roomPubkey },
      data: {
        totalPool: {
          increment: amount,
        },
      },
    });

    // Update Redis cache
    const moonPool = event.moonPool.toString();
    const jeetPool = event.jeetPool.toString();
    await cacheRoom(roomPubkey, { moonPool, jeetPool });

    await publishRoomUpdate(roomPubkey, {
      type: 'BetPlaced',
      user: userPubkey,
      side,
      amount: amount.toString(),
      moonPool,
      jeetPool,
    });

    // Upsert user profile
    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: { userPubkey, totalBets: 1 },
      update: { totalBets: { increment: 1 } },
    });

    betsPlacedTotal.inc({ side });
    betsVolumeTotal.inc(Number(amount));

    logger.info({ msg: 'BetPlaced processed', roomPubkey, userPubkey, side, amount: amount.toString() });
  } finally {
    end();
  }
}

async function handleRoomSettled(event: RoomSettledEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'RoomSettled' });
  try {
    const roomPubkey = event.room.toBase58();
    const winner = event.winner === 0 ? 'moon' : 'jeet';
    const finalPrice = BigInt(event.finalPrice.toString());
    const twapFinalPrice = BigInt(event.twapFinalPrice.toString());
    const totalPool = BigInt(event.totalPool.toString());
    const platformFee = BigInt(event.platformFee.toString());
    const payoutPool = totalPool - platformFee;

    // Fetch winning bets
    const winningBets = await prisma.bet.findMany({
      where: { roomPubkey, side: winner },
    });

    const winningPool = winningBets.reduce((sum, b) => sum + b.amount, BigInt(0));

    // Compute and store individual payouts
    for (const bet of winningBets) {
      if (winningPool === BigInt(0)) continue;
      const payout = (bet.amount * payoutPool) / winningPool;

      const existingPayout = await prisma.payout.findFirst({
        where: { roomPubkey, userPubkey: bet.userPubkey },
      });
      if (existingPayout) {
        await prisma.payout.update({
          where: { id: existingPayout.id },
          data: { amount: payout },
        });
      } else {
        await prisma.payout.create({
          data: {
            roomPubkey,
            userPubkey: bet.userPubkey,
            amount: payout,
          },
        });
      }
    }

    // Update losers' stats
    const losingBets = await prisma.bet.findMany({
      where: { roomPubkey, side: winner === 'moon' ? 'jeet' : 'moon' },
    });

    for (const bet of losingBets) {
      await prisma.userProfile.upsert({
        where: { userPubkey: bet.userPubkey },
        create: {
          userPubkey: bet.userPubkey,
          losses: 1,
          profit: -bet.amount,
        },
        update: {
          losses: { increment: 1 },
          profit: { decrement: bet.amount },
        },
      });
      await updateLeaderboard(bet.userPubkey, -bet.amount);
    }

    // Mark room settled in DB (including twapFinalPrice)
    await prisma.room.update({
      where: { roomPubkey },
      data: {
        status: 'settled',
        winner,
        finalPrice,
        twapFinalPrice,
        platformFee,
      },
    });

    // Update Redis cache
    await cacheRoom(roomPubkey, {
      status: 'settled',
      winner,
      finalPrice: finalPrice.toString(),
      twapFinalPrice: twapFinalPrice.toString(),
    });

    await publishRoomUpdate(roomPubkey, {
      type: 'RoomSettled',
      winner,
      finalPrice: finalPrice.toString(),
      twapFinalPrice: twapFinalPrice.toString(),
      totalPool: totalPool.toString(),
      platformFee: platformFee.toString(),
    });

    roomsSettledTotal.inc({ winner });

    const activeCount = await prisma.room.count({ where: { status: 'active' } });
    activeRoomsGauge.set(activeCount);

    logger.info({ msg: 'RoomSettled processed', roomPubkey, winner, finalPrice: finalPrice.toString(), twapFinalPrice: twapFinalPrice.toString() });
  } finally {
    end();
  }
}

async function handleWinningsClaimed(event: WingsClaimedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'WinningsClaimed' });
  try {
    const roomPubkey = event.room.toBase58();
    const userPubkey = event.user.toBase58();
    const amount = BigInt(event.amount.toString());

    // Mark bet as claimed
    await prisma.bet.updateMany({
      where: { roomPubkey, userPubkey },
      data: { claimed: true },
    });

    // Mark payout as claimed
    await prisma.payout.updateMany({
      where: { roomPubkey, userPubkey },
      data: { claimedAt: new Date() },
    });

    // Update user profile: wins + profit
    // Sum ALL bets for this user in this room (supports multi-bet per user)
    const userBets = await prisma.bet.findMany({
      where: { roomPubkey, userPubkey },
    });
    const totalBetAmount = userBets.reduce((sum, b) => sum + b.amount, BigInt(0));
    const profitGain = totalBetAmount > BigInt(0) ? amount - totalBetAmount : amount;

    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        wins: 1,
        profit: profitGain,
      },
      update: {
        wins: { increment: 1 },
        profit: { increment: profitGain },
      },
    });

    await updateLeaderboard(userPubkey, profitGain);

    await publishRoomUpdate(roomPubkey, {
      type: 'WinningsClaimed',
      user: userPubkey,
      amount: amount.toString(),
    });

    logger.info({ msg: 'WinningsClaimed processed', roomPubkey, userPubkey, amount: amount.toString() });
  } finally {
    end();
  }
}

/**
 * Phase 3.3: Handle PlatformPaused event.
 */
async function handlePlatformPaused(event: PlatformPausedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'PlatformPaused' });
  try {
    const status = event.paused ? 'paused' : 'active';
    logger.info({ msg: `Platform ${status}`, paused: event.paused });

    // Broadcast to all connected WebSocket clients
    await publishRoomUpdate('__platform__', {
      type: 'PlatformPaused',
      paused: event.paused,
    });
  } finally {
    end();
  }
}

/**
 * Phase 3.5: Handle ReputationUpdated event.
 */
async function handleReputationUpdated(event: ReputationUpdatedEvent): Promise<void> {
  const end = eventProcessingDuration.startTimer({ event_type: 'ReputationUpdated' });
  try {
    const userPubkey = event.user.toBase58();
    const tierMap = ['D', 'C', 'B', 'A', 'S'];
    const tier = tierMap[event.tier] ?? 'D';
    const totalBets = BigInt(event.totalBets.toString());
    const totalWins = BigInt(event.totalWins.toString());

    // Upsert reputation record
    await prisma.reputation.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        tier,
        totalBets,
        totalWins,
      },
      update: {
        tier,
        totalBets,
        totalWins,
        lastEval: new Date(),
      },
    });

    // Also update the user profile with the tier
    await prisma.userProfile.upsert({
      where: { userPubkey },
      create: {
        userPubkey,
        trenchScore: tier,
      },
      update: {
        trenchScore: tier,
      },
    });

    logger.info({
      msg: 'ReputationUpdated processed',
      userPubkey,
      tier,
      totalBets: totalBets.toString(),
      totalWins: totalWins.toString(),
    });

    await publishRoomUpdate('__reputation__', {
      type: 'ReputationUpdated',
      user: userPubkey,
      tier,
    });
  } finally {
    end();
  }
}

let subscriptionId: number | null = null;

export function startEventListener(
  connection: Connection,
  eventParser: anchor.EventParser
): void {
  const programId = new PublicKey(config.solana.programId);

  subscriptionId = connection.onLogs(
    programId,
    async (logs: Logs) => {
      const { signature, logs: logLines, err } = logs;

      if (err) {
        logger.warn({ msg: 'Log with error skipped', signature, err });
        return;
      }

      // Idempotency guard
      if (await isAlreadyProcessed(signature)) {
        logger.debug({ msg: 'Duplicate tx skipped', signature });
        return;
      }

      // Parse Anchor events from log lines
      try {
        const events = eventParser.parseLogs(logLines);

        for (const event of events) {
          logger.debug({ msg: 'Anchor event received', name: event.name, signature });

          switch (event.name) {
            case 'RoomCreated':
              await handleRoomCreated(event.data as RoomCreatedEvent);
              break;
            case 'BetPlaced':
              await handleBetPlaced(event.data as BetPlacedEvent);
              break;
            case 'RoomSettled':
              await handleRoomSettled(event.data as RoomSettledEvent);
              break;
            case 'WinningsClaimed':
              await handleWinningsClaimed(event.data as WingsClaimedEvent);
              break;
            case 'PlatformPaused':
              await handlePlatformPaused(event.data as PlatformPausedEvent);
              break;
            case 'ReputationUpdated':
              await handleReputationUpdated(event.data as ReputationUpdatedEvent);
              break;
            default:
              logger.warn({ msg: 'Unknown event', name: event.name });
          }
        }

        await markProcessed(signature);
      } catch (err: any) {
        logger.error({ msg: 'Event processing error', signature, err: err?.message, stack: err?.stack });
      }
    },
    'confirmed'
  );

  logger.info({ msg: 'Event listener started', programId: programId.toBase58() });
}

export async function stopEventListener(connection: Connection): Promise<void> {
  if (subscriptionId !== null) {
    await connection.removeOnLogsListener(subscriptionId);
    subscriptionId = null;
    logger.info('Event listener stopped');
  }
}
